function Information() {
  return (
    <div className="page card">
      <h2>ℹ️ Information</h2>
      <p>
        A carbon footprint represents the total greenhouse gases
        generated by human activities. Reducing it helps fight
        climate change and ensures a sustainable future.
      </p>
    </div>
  );
}

export default Information;
